# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f41624652031fb20c5a2dde1d6052cda4259c1d97f629a5e40413c5a3cdb553b08a5eea3db58a973138f70f819d04691b8924830af3d1561f92fe7718f1ae3c

test:
  secret_key_base: 04a8d191f44061044eff379b18257afa2082dd7e854b0ec2bcd6bb2337263fdb922240b7cd5f9ba4ae77c3396639a95fc29c25905af816956a0de901148b2b4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
